//@ pragma UseQApplication
// Deployed by 5-dotfiles.sh into ~/.config/quickshell/dock/. Run as its own
// named Quickshell config (`qs -c dock`), not the default `~/.config/
// quickshell/shell.qml` slot -- leaves that free for anything else you point
// Quickshell at later.
//
// Trimmed down from mylinuxforwork/dotfiles' own shell.qml, which loads its
// whole app suite (Welcome/Power/Sidebar/Calendar/Wallpaper/Statusbar) from
// here -- this repo already has equivalents for all of those (wlogout,
// hyprlock, eww, waypaper, waybar), so only DockApp (and the CustomTheme
// singleton it reads colors from) is ported. See DockApp/ and CustomTheme/
// in this directory -- both copied verbatim from upstream; only the color
// source they read (~/.config/ml4w/colors/colors.json) is this repo's own,
// generated by Matugen -- see the README's color theming section and
// dotfiles/matugen/templates/quickshell-dock-colors.json.
import Quickshell
import Quickshell.Io
import "DockApp"
import "CustomTheme"

ShellRoot {
    // qs ipc -c dock call theme-manager reload -- wired into theme.sh's
    // deploy_colors() and Matugen's post_hook, same as every other app's
    // reload signal (killall -SIGUSR2 waybar, hyprctl reload, etc.)
    IpcHandler {
        target: "theme-manager"
        function reload(): void {
            Theme.reloadTheme()
        }
    }

    // Creates the dock window only while the dock is enabled in dock.json.
    DockLoader {}
}
